package com.studyprogram.model;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class QuestionTest {

    private static Question.Builder minimal() {
        return Question.builder()
                .topic(Topic.VARIABLES)
                .prompt("What is 1 + 1?")
                .answer("2");
    }

    // ── Builder validation ────────────────────────────────────────────────────

    @Test
    void buildSucceeds() {
        assertDoesNotThrow(() -> minimal().build());
    }

    @Test
    void missingTopicThrows() {
        assertThrows(IllegalStateException.class, () ->
                Question.builder().prompt("?").answer("x").build());
    }

    @Test
    void missingPromptThrows() {
        assertThrows(IllegalStateException.class, () ->
                Question.builder().topic(Topic.VARIABLES).answer("x").build());
    }

    @Test
    void missingAnswerThrows() {
        assertThrows(IllegalStateException.class, () ->
                Question.builder().topic(Topic.VARIABLES).prompt("?").build());
    }

    // ── Answer normalisation (bug fix: must preserve case) ────────────────────

    @Test
    void answerPreservesCase() {
        Question q = minimal().answer("JAVA4").build();
        assertEquals("JAVA4", q.getAnswer(),
                "Stored answer must preserve original case for correct display in feedback");
    }

    @Test
    void answerTrimsWhitespace() {
        Question q = minimal().answer("  42  ").build();
        assertEquals("42", q.getAnswer());
    }

    @Test
    void answerDoesNotLowercase() {
        Question q = minimal().answer("Hello, World!").build();
        assertEquals("Hello, World!", q.getAnswer());
    }

    @Test
    void alternativePreservesCase() {
        Question q = minimal().alternative("  Forty-Two  ").build();
        assertEquals("Forty-Two", q.getAlternativeAnswers().get(0));
    }

    // ── Defaults ──────────────────────────────────────────────────────────────

    @Test
    void defaultTypeIsMultipleChoice() {
        Question q = minimal().build();
        assertEquals(QuestionType.MULTIPLE_CHOICE, q.getType());
    }

    @Test
    void defaultDifficultyIsOne() {
        Question q = minimal().build();
        assertEquals(1, q.getDifficulty());
    }

    @Test
    void defaultExplanationIsEmpty() {
        Question q = minimal().build();
        assertEquals("", q.getExplanation());
    }

    @Test
    void idIsAutoGeneratedWhenNotSet() {
        Question q = minimal().build();
        assertNotNull(q.getId());
        assertFalse(q.getId().isBlank());
    }

    @Test
    void explicitIdOverridesAutoGenerated() {
        Question q = minimal().id("my-custom-id").build();
        assertEquals("my-custom-id", q.getId());
    }

    // ── Code / hasCode ────────────────────────────────────────────────────────

    @Test
    void hasCodeFalseByDefault() {
        assertFalse(minimal().build().hasCode());
    }

    @Test
    void hasCodeTrueWhenSet() {
        Question q = minimal().code("int x = 1;").build();
        assertTrue(q.hasCode());
    }

    @Test
    void hasCodeFalseForBlankCode() {
        Question q = minimal().code("   ").build();
        assertFalse(q.hasCode());
    }

    // ── Multiple-choice detection ─────────────────────────────────────────────

    @Test
    void isMultipleChoiceFalseWithNoChoices() {
        Question q = minimal().type(QuestionType.TRACING).build();
        assertFalse(q.isMultipleChoice());
    }

    @Test
    void isMultipleChoiceTrueWhenChoicesSet() {
        Question q = minimal()
                .choices("A", "B", "C", "D")
                .build();
        assertTrue(q.isMultipleChoice());
        assertEquals(4, q.getChoices().size());
    }

    @Test
    void choicesReplacedBySecondCall() {
        Question q = minimal()
                .choices("1", "2", "3", "4")
                .choices("A", "B", "C", "D")
                .build();
        assertEquals("A", q.getChoices().get(0));
        assertEquals(4, q.getChoices().size());
    }

    // ── Immutability ──────────────────────────────────────────────────────────

    @Test
    void choiceListIsUnmodifiable() {
        Question q = minimal().choices("A", "B", "C", "D").build();
        assertThrows(UnsupportedOperationException.class, () -> q.getChoices().add("E"));
    }

    @Test
    void alternativeListIsUnmodifiable() {
        Question q = minimal().alternative("two").build();
        assertThrows(UnsupportedOperationException.class, () -> q.getAlternativeAnswers().add("tres"));
    }

    @Test
    void hintListIsUnmodifiable() {
        Question q = minimal().hint("try adding").build();
        assertThrows(UnsupportedOperationException.class, () -> q.getHints().add("another"));
    }

    // ── Hints ────────────────────────────────────────────────────────────────

    @Test
    void multipleHintsAreStored() {
        Question q = minimal().hint("first").hint("second").hint("third").build();
        assertEquals(List.of("first", "second", "third"), q.getHints());
    }
}
