package com.studyprogram.report;

import com.studyprogram.core.Curriculum;
import com.studyprogram.model.*;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.*;

/**
 * Renders a self-contained HTML progress report (inline CSS, Java-generated SVG,
 * no external resources) that the student opens in any browser: summary stats,
 * an activity calendar, accuracy over time, per-topic mastery, accuracy by
 * difficulty and question type, and a "what to work on next" section derived
 * from the prerequisite graph.
 */
public class HtmlReportGenerator {

    private static final DateTimeFormatter DAY = DateTimeFormatter.ISO_LOCAL_DATE;

    /** Convenience overload without calibration flags. */
    public Path generate(StudentProfile profile, List<AttemptRecord> attempts, Path outFile)
            throws IOException {
        return generate(profile, attempts, List.of(), outFile);
    }

    public Path generate(StudentProfile profile, List<AttemptRecord> attempts,
                         List<String> flaggedQuestions, Path outFile)
            throws IOException {
        StringBuilder h = new StringBuilder(64_000);

        h.append("<!DOCTYPE html><html><head><meta charset='utf-8'>")
         .append("<title>Java Study Progress — ").append(esc(profile.getName())).append("</title>")
         .append("<style>").append(CSS).append("</style></head><body><div class='page'>");

        header(h, profile, attempts);
        activityCalendar(h, attempts);
        accuracyOverTime(h, attempts);
        masteryByTopic(h, profile);
        accuracyBreakdowns(h, attempts);
        workOnNext(h, profile);

        if (!flaggedQuestions.isEmpty()) {
            h.append("<h2>Question calibration (for instructors)</h2><p class='dim'>")
             .append("These questions' measured difficulty has drifted from their label — ")
             .append("worth a wording or difficulty review.</p><ul>");
            for (String f : flaggedQuestions) {
                h.append("<li class='dim'>").append(esc(f)).append("</li>");
            }
            h.append("</ul>");
        }

        h.append("<footer>Generated by Java Study Program on ")
         .append(LocalDate.now().format(DAY)).append("</footer></div></body></html>");

        Files.createDirectories(outFile.toAbsolutePath().getParent());
        Files.writeString(outFile, h.toString(), StandardCharsets.UTF_8);
        return outFile;
    }

    // ── Sections ─────────────────────────────────────────────────────────────

    private void header(StringBuilder h, StudentProfile p, List<AttemptRecord> attempts) {
        long answered = attempts.stream().filter(AttemptRecord::isAnswered).count();
        long correct  = attempts.stream().filter(AttemptRecord::isCorrect).count();
        long codingSolved = attempts.stream()
                .filter(a -> a.getType() == QuestionType.CODING && a.isCorrect()).count();
        Set<LocalDate> studyDays = studyDays(attempts);
        int streak = currentStreak(studyDays);

        h.append("<h1>").append(esc(p.getName())).append("'s Java Progress</h1><div class='tiles'>");
        tile(h, String.valueOf(answered), "questions answered");
        tile(h, answered == 0 ? "–" : Math.round(100.0 * correct / answered) + "%", "accuracy");
        tile(h, String.valueOf(codingSolved), "programs written & passed");
        tile(h, String.valueOf(studyDays.size()), "study days");
        tile(h, String.valueOf(streak), "day streak");
        tile(h, p.getBossesCleared().size() + "/5", "bosses cleared");
        h.append("</div>");
    }

    /** GitHub-style activity grid for the last 26 weeks. */
    private void activityCalendar(StringBuilder h, List<AttemptRecord> attempts) {
        Map<LocalDate, Integer> perDay = new HashMap<>();
        for (AttemptRecord a : attempts) {
            if (a.getTs() != null) perDay.merge(a.getTs().toLocalDate(), 1, Integer::sum);
        }
        h.append("<h2>Activity — last 26 weeks</h2>");
        LocalDate today = LocalDate.now();
        LocalDate start = today.minusWeeks(26);
        // align to the Monday on/before start
        start = start.minusDays(start.getDayOfWeek().getValue() - 1);

        int cell = 11, gap = 2;
        int weeks = 27;
        h.append("<svg width='").append(weeks * (cell + gap)).append("' height='")
         .append(7 * (cell + gap)).append("'>");
        for (int w = 0; w < weeks; w++) {
            for (int d = 0; d < 7; d++) {
                LocalDate day = start.plusWeeks(w).plusDays(d);
                if (day.isAfter(today)) continue;
                int n = perDay.getOrDefault(day, 0);
                String fill = n == 0 ? "#e8e8e8" : n < 5 ? "#b7e2b1" : n < 15 ? "#68bb59" : "#2e7d32";
                h.append("<rect x='").append(w * (cell + gap)).append("' y='").append(d * (cell + gap))
                 .append("' width='").append(cell).append("' height='").append(cell)
                 .append("' rx='2' fill='").append(fill).append("'><title>")
                 .append(day.format(DAY)).append(": ").append(n).append(" attempt(s)</title></rect>");
            }
        }
        h.append("</svg>");
    }

    /** Attempts per day (bars) with a 7-day rolling accuracy line, last 60 active-range days. */
    private void accuracyOverTime(StringBuilder h, List<AttemptRecord> attempts) {
        TreeMap<LocalDate, int[]> byDay = new TreeMap<>();   // {answered, correct}
        for (AttemptRecord a : attempts) {
            if (a.getTs() == null || !a.isAnswered()) continue;
            int[] c = byDay.computeIfAbsent(a.getTs().toLocalDate(), k -> new int[2]);
            c[0]++;
            if (a.isCorrect()) c[1]++;
        }
        h.append("<h2>Accuracy over time</h2>");
        if (byDay.isEmpty()) {
            h.append("<p class='dim'>No answered questions yet — the chart appears once you study.</p>");
            return;
        }
        LocalDate end = byDay.lastKey();
        LocalDate begin = end.minusDays(59);
        List<LocalDate> days = new ArrayList<>();
        for (LocalDate d = begin; !d.isAfter(end); d = d.plusDays(1)) days.add(d);

        int wch = 12, height = 160, axis = 30;
        int width = days.size() * wch + axis;
        int maxCount = 1;
        for (LocalDate d : days) maxCount = Math.max(maxCount, byDay.getOrDefault(d, new int[2])[0]);

        h.append("<svg width='").append(width).append("' height='").append(height + 20).append("'>");
        // bars: attempts per day
        for (int i = 0; i < days.size(); i++) {
            int n = byDay.getOrDefault(days.get(i), new int[2])[0];
            if (n == 0) continue;
            int bh = (int) Math.round((double) n / maxCount * (height - 20));
            h.append("<rect x='").append(axis + i * wch).append("' y='").append(height - bh)
             .append("' width='").append(wch - 3).append("' height='").append(bh)
             .append("' fill='#a8c7e7'><title>").append(days.get(i).format(DAY)).append(": ")
             .append(n).append(" answered</title></rect>");
        }
        // rolling 7-day accuracy line
        StringBuilder pts = new StringBuilder();
        for (int i = 0; i < days.size(); i++) {
            int ans = 0, cor = 0;
            for (int j = Math.max(0, i - 6); j <= i; j++) {
                int[] c = byDay.getOrDefault(days.get(j), new int[2]);
                ans += c[0];
                cor += c[1];
            }
            if (ans == 0) continue;
            double acc = (double) cor / ans;
            int x = axis + i * wch + wch / 2;
            int y = (int) Math.round(height - acc * (height - 20));
            pts.append(pts.length() == 0 ? "" : " ").append(x).append(",").append(y);
        }
        h.append("<polyline points='").append(pts)
         .append("' fill='none' stroke='#c0392b' stroke-width='2'/>");
        h.append("<text x='0' y='14' class='axis'>100%</text>")
         .append("<text x='0' y='").append(height).append("' class='axis'>0%</text>")
         .append("</svg><p class='dim'>Blue bars: questions answered per day (max ")
         .append(maxCount).append("/day). Red line: 7-day rolling accuracy.</p>");
    }

    private void masteryByTopic(StringBuilder h, StudentProfile profile) {
        h.append("<h2>Mastery by topic</h2>");
        Map<Topic, TopicPerformance> perf = profile.getPerformance();
        String[] levelNames = {"", "Beginner", "Elementary", "Intermediate", "Advanced", "Expert"};
        for (int level = 1; level <= 5; level++) {
            final int lv = level;
            List<Topic> group = Arrays.stream(Topic.values())
                    .filter(t -> t.baseLevel == lv)
                    .filter(t -> perf.containsKey(t) && perf.get(t).getAttempts() > 0)
                    .toList();
            if (group.isEmpty()) continue;
            h.append("<h3>").append(levelNames[level]).append("</h3>");
            for (Topic t : group) {
                TopicPerformance p = perf.get(t);
                int pct = (int) Math.round(p.getMasteryScore() * 100);
                String color = pct >= 80 ? "#2e7d32" : pct >= 40 ? "#f0a500" : "#c0392b";
                h.append("<div class='mrow'><span class='mname'>").append(esc(t.displayName))
                 .append("</span><span class='mbar'><span style='width:").append(pct)
                 .append("%;background:").append(color).append("'></span></span><span class='mpct'>")
                 .append(pct).append("% <span class='dim'>(").append(p.getCorrect()).append("/")
                 .append(p.getAttempts()).append(p.getSkipped() > 0
                         ? ", " + p.getSkipped() + " skipped" : "")
                 .append(")</span></span></div>");
            }
        }
        if (profile.getPerformance().values().stream().noneMatch(p -> p.getAttempts() > 0)) {
            h.append("<p class='dim'>No attempts recorded yet.</p>");
        }
    }

    private void accuracyBreakdowns(StringBuilder h, List<AttemptRecord> attempts) {
        h.append("<h2>Accuracy by difficulty and question type</h2><div class='cols'>");
        // by difficulty
        h.append("<div><h3>By difficulty</h3>");
        for (int d = 1; d <= 5; d++) {
            final int dd = d;
            long ans = attempts.stream().filter(a -> a.getDifficulty() == dd && a.isAnswered()).count();
            long cor = attempts.stream().filter(a -> a.getDifficulty() == dd && a.isCorrect()).count();
            bar(h, "★".repeat(d), ans, cor);
        }
        h.append("</div><div><h3>By type</h3>");
        for (QuestionType t : QuestionType.values()) {
            long ans = attempts.stream().filter(a -> a.getType() == t && a.isAnswered()).count();
            long cor = attempts.stream().filter(a -> a.getType() == t && a.isCorrect()).count();
            if (ans > 0) bar(h, t.displayName, ans, cor);
        }
        h.append("</div></div>");
    }

    private void workOnNext(StringBuilder h, StudentProfile profile) {
        h.append("<h2>What to work on next</h2>");
        List<Topic> frontier = Curriculum.frontier(profile);
        if (frontier.isEmpty()) {
            h.append("<p>Everything unlocked is mastered — impressive. Time for the advanced topics!</p>");
            return;
        }
        h.append("<ol>");
        for (Topic t : frontier.subList(0, Math.min(8, frontier.size()))) {
            int blocked = Curriculum.downstreamBlocked(t, profile);
            h.append("<li><b>").append(esc(t.displayName)).append("</b> — ").append(esc(t.description));
            if (blocked > 0) {
                h.append(" <span class='dim'>(unlocks progress toward ").append(blocked)
                 .append(" more topic").append(blocked == 1 ? "" : "s").append(")</span>");
            }
            h.append("</li>");
        }
        h.append("</ol>");
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private static Set<LocalDate> studyDays(List<AttemptRecord> attempts) {
        Set<LocalDate> days = new TreeSet<>();
        for (AttemptRecord a : attempts) if (a.getTs() != null) days.add(a.getTs().toLocalDate());
        return days;
    }

    private static int currentStreak(Set<LocalDate> days) {
        LocalDate d = LocalDate.now();
        if (!days.contains(d)) d = d.minusDays(1);   // today not studied yet doesn't break it
        int streak = 0;
        while (days.contains(d)) {
            streak++;
            d = d.minusDays(1);
        }
        return streak;
    }

    private static void tile(StringBuilder h, String value, String label) {
        h.append("<div class='tile'><div class='big'>").append(value)
         .append("</div><div class='dim'>").append(label).append("</div></div>");
    }

    private static void bar(StringBuilder h, String label, long answered, long correct) {
        int pct = answered == 0 ? 0 : (int) Math.round(100.0 * correct / answered);
        String color = pct >= 80 ? "#2e7d32" : pct >= 40 ? "#f0a500" : "#c0392b";
        h.append("<div class='mrow'><span class='mname'>").append(esc(label))
         .append("</span><span class='mbar'><span style='width:").append(pct)
         .append("%;background:").append(color).append("'></span></span><span class='mpct'>");
        if (answered == 0) h.append("<span class='dim'>no data</span>");
        else h.append(pct).append("% <span class='dim'>(").append(correct).append("/")
              .append(answered).append(")</span>");
        h.append("</span></div>");
    }

    private static String esc(String s) {
        return s == null ? "" : s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }

    private static final String CSS = """
            body { font-family: system-ui, -apple-system, 'Segoe UI', sans-serif; margin: 0;
                   background: #f5f5f2; color: #222; }
            .page { max-width: 880px; margin: 0 auto; padding: 24px; }
            h1 { margin-top: 8px; } h2 { margin-top: 36px; border-bottom: 2px solid #ddd;
                 padding-bottom: 4px; } h3 { margin-bottom: 6px; }
            .tiles { display: flex; gap: 12px; flex-wrap: wrap; }
            .tile { background: #fff; border-radius: 10px; padding: 14px 18px;
                    box-shadow: 0 1px 3px rgba(0,0,0,.12); min-width: 110px; }
            .big { font-size: 28px; font-weight: 700; }
            .dim { color: #777; font-size: 13px; }
            .mrow { display: flex; align-items: center; gap: 10px; margin: 4px 0; }
            .mname { flex: 0 0 240px; font-size: 14px; }
            .mbar { flex: 1; height: 12px; background: #e4e4e0; border-radius: 6px;
                    overflow: hidden; display: block; }
            .mbar span { display: block; height: 100%; border-radius: 6px; }
            .mpct { flex: 0 0 150px; font-size: 13px; }
            .cols { display: flex; gap: 40px; flex-wrap: wrap; }
            .cols > div { flex: 1; min-width: 300px; }
            svg { background: #fff; border-radius: 8px; padding: 8px;
                  box-shadow: 0 1px 3px rgba(0,0,0,.12); }
            svg text.axis { font-size: 11px; fill: #777; }
            footer { margin-top: 40px; color: #999; font-size: 12px; }
            """;
}
